region: us-east-1
firebase_api_key: AAAAWjbFHGk:APA91bHNNrCDuLKe1aUL8CTjVk2l1FZzNv9U2mwpt9imx9G7kY2c_SoqxWRzN_tJAFouw8ar1qPjXPvPTRWGumHroUwY2ZHyhZ2n1DiHz_9tHH2TeTMlPRiV5vlj7Z0WI0EalJDFPXIm
firebase_sender_id: "387465944169"
facebook_app_id: "2278011852232737"
google_app_id: "206036539243-upk8p7t3fi5o52fjmp7qlbtvio19k455.apps.googleusercontent.com"